version: "3.8"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    depends_on:
      - wordpress
    volumes:
      - website:/var/www/html:delegate
    ports:
      - 443:443
    networks:
      - network

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - website:/var/www/html:delegate
    networks:
      - network
    expose:
      - 9000
    environment:
      - SQL_DB = $SQL_DB
      - SQL_USER = $SQL_USER
      - SQL_PASSWORD = $SQL_PASSWORD

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - database:/var/lib/mysql:delegate
    networks:
      - network
    expose:
      - 3306
    environment:
      - SQL_DB = $SQL_DB
      - SQL_USER = $SQL_USER
      - SQL_PASSWORD = $SQL_PASSWORD

volumes:
  website:
    driver: local
  database:
    driver: local

networks:
  network:
    driver: bridge
