version: "3.8"

volumes:
  wordpress:

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - wordpress:/var/www/wordpress
    expose:
      - "9000"
    restart: on-failure
