version: "3.9"
name: inception

services:
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      args:
        - LOGIN=${LOGIN}
    depends_on:
      - wordpress
    volumes:
      - website:/var/www/html
    networks:
      - 42net
    ports:
      - 443:443

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - website:/var/www/html
    networks:
      - 42net
    expose:
      - 9000
    env_file: .env

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      args:
        - SQL_DB=${SQL_DB}
        - SQL_PWD=${SQL_PWD}
        - SQL_USER=${SQL_USER}
        - SQL_ROOT_PWD=${SQL_ROOT_PWD}
    volumes:
      - database:/var/lib/mysql
    networks:
      - 42net
    expose:
      - 3306
    env_file: .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  website:
    name: website
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/website'
  database:
    name: database
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/database'

networks:
  42net:
