version: "3.9"

services:
  nginx:
    container_name: nginx
    hostname: nginx
    build: requirements/nginx
    depends_on:
      - wordpress
    volumes:
      - website:/var/www/html:delegate
    ports:
      - 443:443
    networks:
      - incNet

  wordpress:
    container_name: wordpress
    hostname: wordpress
    build: requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - website:/var/www/html:delegate
    networks:
      - incNet
    expose:
      - 9000

  mariadb:
    container_name: mariadb
    hostname: mariadb
    build:
      context: requirements/mariadb
      args:
        - SQL_DB=${SQL_DB}
        - SQL_USER=${SQL_USER}
        - SQL_PASS=${SQL_PASS}
    volumes:
      - database:/var/lib/mysql:delegate
    networks:
      - incNet
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password

volumes:
  website:
    driver: local
  database:
    driver: local

networks:
  incNet:
    driver: bridge
