CREATE DATABASE IF NOT EXISTS db;
CREATE USER IF NOT EXISTS 'user'@'wordpress.srcs_incNet' IDENTIFIED BY 'pass';
GRANT ALL PRIVILEGES ON db.* TO 'user'@'wordpress.srcs_incNet' IDENTIFIED BY 'pass';
FLUSH PRIVILEGES;
